/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Entity.Administrator;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class SearchRecordPage extends javax.swing.JFrame {

    /**
     * Creates new form SearchRecordPage
     */
    public SearchRecordPage() {
        initComponents();
        lblStatus.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        ORDERID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        custPaymentTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        custOrderTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ORDERID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ORDERIDActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ORDER ID: ");

        custPaymentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID", "PayID", "CreditCardName", "CreditCardNumber", "Total"
            }
        ));
        jScrollPane1.setViewportView(custPaymentTable);

        custOrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ORDERID", "DAY&DATE", "TIME", "ORDERTAILS"
            }
        ));
        jScrollPane2.setViewportView(custOrderTable);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblStatus.setText("lblStatus");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addComponent(ORDERID, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatus)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ORDERID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        AdminHomePage adminHomePage = new AdminHomePage();
        
        this.dispose();
        
        adminHomePage.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ORDERIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ORDERIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ORDERIDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Administrator administrator = new Administrator();
            
            if("".equals(ORDERID.getText())){
                System.out.println("Empty");
                
                lblStatus.setVisible(true);
                lblStatus.setText("Pls Enter Require Blank!!!!");
            }else{
            try {
                boolean valid = administrator.searchCustPayment(ORDERID.getText());
                
                if(valid){
                    System.out.println("HALLO WORLD");
                    File FoodFile = new File("creditcarddetail.txt");
                    
                    BufferedReader br = new BufferedReader(new FileReader(FoodFile));
                    
                    String strHeader = br.readLine().trim();
                    String[] columnHeader = strHeader.split(":");
                    DefaultTableModel tModel = (DefaultTableModel) custPaymentTable.getModel();
                    
                    tModel.setColumnIdentifiers(columnHeader);
                    
                    //Save Each line of data into adminRow Arrayin x;x;x
                    Object[] tableRow = br.lines().toArray();
                    for(int i=0; i<tableRow.length;i++){
                        String rows = tableRow[i].toString().trim();
                        //System.out.println(rows);
                        String[] splitRows = rows.split(":");
                        
                        if(splitRows[0].equals(ORDERID.getText())){
                            tModel.setRowCount(0);
                            tModel.addRow(splitRows);

                            lblStatus.setVisible(true);
                            lblStatus.setText("Id Found!!");
                        }
                        
                    }
                    System.out.println("HALLO WORLD");
                    
                    File orderDetailFile = new File("orderdetail.txt");
                    BufferedReader br1 = new BufferedReader(new FileReader(orderDetailFile));
                    
                    String strHeader1 = br1.readLine().trim();
                    String[] columnHeader1 = strHeader1.split("/");
                    DefaultTableModel tModel2 = (DefaultTableModel) custOrderTable.getModel();
                    
                    tModel2.setColumnIdentifiers(columnHeader1);
                    
                    //Save Each line of data into adminRow Arrayin x;x;x
                    Object[] tableRow1 = br1.lines().toArray();
                    
                    
                    for(int i=0; i<tableRow1.length;i++){
                        String rows = tableRow1[i].toString().trim();
                        //System.out.println(rows);
                        String[] splitRows1 = rows.split("/");
                        System.out.println(splitRows1[0]);
                        System.out.println(splitRows1[1]);
                        System.out.println(splitRows1[2]);
                        System.out.println(splitRows1[3]);

                        
                        if(splitRows1[0].equals(ORDERID.getText())){
                            
                            tModel2.setRowCount(0);
                            tModel2.addRow(splitRows1);
                            
                            System.out.println(Arrays.toString(splitRows1));

                            lblStatus.setVisible(true);
                            lblStatus.setText("Id Found!!");
                        }
                        
                    }
                    
                    
                    
                    
                    
                    
                }else{
                    
                    lblStatus.setVisible(true);
                    lblStatus.setText("Id Not Exist!!");
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(SearchRecordPage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(SearchRecordPage.class.getName()).log(Level.SEVERE, null, ex);
            }
                
                
            }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel tModel = (DefaultTableModel) custOrderTable.getModel(); 
        DefaultTableModel tMode2 = (DefaultTableModel) custPaymentTable.getModel(); 


        tModel.setRowCount(0);
        tMode2.setRowCount(0);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchRecordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchRecordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchRecordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchRecordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchRecordPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ORDERID;
    private javax.swing.JTable custOrderTable;
    private javax.swing.JTable custPaymentTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
